### PR TITLE
adding missing subject lists

### PR DESCRIPTION
**Pull request by prakashujjwal1010**
fixing #5 .
please review if the added missing subject lists are having correct credits or not before merging.

### CODE REVIEW

**Comment by anuj-aggarwal** [comment]
The check for these missing semesters is outdated, so the app will still show "Data not available".

**Comment by uditarora** [comment]
@prakashujjwal1010 thank you for adding the data! May I know where you got the data for the subject categories of these subjects you've added?

Also, @anuj-aggarwal is right. calculator.js will have to be modified as well. Let me know if you need help with that.

**Comment by prakashujjwal1010** [comment]
@uditarora i got the data from http://updates.collegespace.in/category/syllabus/ but here the subject categories & credits of ice and subject categories of ece are not given.

**Comment by prakashujjwal1010** [comment]
@uditarora  I am deleting the checks for 7th and 8th sem data in calculator.js. you can check it out.

**Comment by uditarora** [comment]
Thank you @prakashujjwal1010 for taking up this issue, and the PR.

**Pull request merged**
